//! Anisette / Client Provisioning Data (CPD) for Apple `GrandSlam`.
//!
//! Apple's `GrandSlam` authentication requires device metadata (CPD) embedded
//! in the SRP request plist. This module generates realistic simulated
//! device data.

mod fields;
mod remote;
mod time;

use crate::domain::error::AppStoreError;
use base64::Engine;
use fields::{AnisetteFields, build_cpd, build_headers, current_locale};
use remote::fetch_remote;
use serde_json::Value as JsonValue;
use std::collections::HashMap;
use time::iso8601_now;

#[cfg(target_os = "macos")]
use super::aoskit::{machine_serial_number, machine_udid, retrieve_otp_headers};
#[cfg(not(target_os = "macos"))]
use super::aoskit_fallback::retrieve_otp_headers;

/// Device provisioning data bundled with HTTP headers.
#[derive(Debug, Clone)]
pub struct AnisetteData {
    /// Extra HTTP headers to attach to `GrandSlam` requests.
    pub headers: HashMap<String, String>,
    /// The `cpd` plist dictionary to embed in SRP request bodies.
    pub cpd: JsonValue,
}

/// Returns the local user's `GeneratedUID` on macOS, if available.
#[cfg(target_os = "macos")]
fn get_local_user_uuid() -> Option<String> {
    let username = std::env::var("USER").ok()?;
    let output = std::process::Command::new("dscl")
        .args([
            "/Search",
            "-read",
            &format!("/Users/{username}"),
            "GeneratedUID",
        ])
        .output()
        .ok()?;
    let stdout = String::from_utf8(output.stdout).ok()?;
    // Parse "GeneratedUID: AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA"
    stdout
        .split_whitespace()
        .nth(1)
        .map(|s| s.trim().to_string())
}

#[cfg(not(target_os = "macos"))]
fn get_local_user_uuid() -> Option<String> {
    None
}

const DEVICE_MODEL: &str = "MacBookPro18,3";
const RINFO: &str = "17106176";
const CLIENT_INFO: &str = "<MacBookPro18,3> <Mac OS X;15.2;24C5089c> <com.apple.AOSKit/282 (com.apple.dt.Xcode/3594.4.19)>";
const FALLBACK_DEVICE_ID: &str = "FEDCBA09-8765-4321-0FED-CBA987654321";

/// Cryptographic OTP tokens (`X-Apple-I-MD*`) bundled together.
struct OtpTokens {
    md: String,
    md_lu: String,
    md_m: String,
}

/// Obtain Anisette data for the current platform/configuration.
///
/// Resolution order:
/// 1. `IPAKEEP_ANISETTE_URL` — fetch from an explicit remote anisette server.
/// 2. macOS — generate locally via `AOSKit` (real OTP tokens).
/// 3. Other platforms — auto-launch the bundled Docker anisette server and
///    fetch from it (`AOSKit` is unavailable, so placeholder tokens would be
///    rejected by Apple).
///
/// # Errors
///
/// Returns an error if a configured/launched anisette server cannot be reached
/// or returns an incomplete payload.
pub async fn resolve_anisette(client: &reqwest::Client) -> Result<AnisetteData, AppStoreError> {
    if let Ok(url) = std::env::var("IPAKEEP_ANISETTE_URL") {
        let url = url.trim();
        if !url.is_empty() {
            return fetch_remote(client, url).await;
        }
    }

    if cfg!(target_os = "macos") {
        // macOS can generate valid OTP tokens locally via AOSKit.
        Ok(generate_anisette())
    } else {
        // Other platforms lack AOSKit; fetch from the Docker anisette server.
        let url = super::anisette_docker::ensure_local_server(client).await?;
        fetch_remote(client, &url).await
    }
}

/// Generate Anisette / CPD data locally (macOS `AOSKit` path).
fn generate_anisette() -> AnisetteData {
    let tokens = otp_tokens();
    let (device_id, serial) = machine_identifiers();

    let fields = AnisetteFields {
        time: iso8601_now(),
        timezone: "UTC".to_string(),
        locale: current_locale(),
        md: tokens.md,
        md_lu: get_local_user_uuid().unwrap_or(tokens.md_lu),
        md_m: tokens.md_m,
        rinfo: RINFO.to_string(),
        device_id,
        serial,
    };

    AnisetteData {
        headers: build_headers(&fields),
        cpd: build_cpd(&fields),
    }
}

/// Resolve the OTP tokens, preferring real `AOSKit` values when available.
///
/// `X-Apple-I-MD` and `X-Apple-I-MD-M` are cryptographic tokens generated by
/// Apple's proprietary CoreADI/AOSKit libraries. On macOS we try to load the
/// real values; on other platforms we fall back to placeholders.
fn otp_tokens() -> OtpTokens {
    let encode = |seed: &str| {
        base64::engine::general_purpose::STANDARD.encode(md5::compute(seed).as_slice())
    };
    let mut tokens = OtpTokens {
        md: encode("ipakeep-mac"),
        md_lu: "A1B2C3D4-E5F6-7890-1234-567890ABCDEF".to_string(),
        md_m: encode(DEVICE_MODEL),
    };

    let Some(headers) = retrieve_otp_headers("-2") else {
        return tokens;
    };

    // AOSUtilities may return keys with or without the `-I-` segment.
    let pick = |primary: &str, fallback: &str| {
        headers
            .get(primary)
            .or_else(|| headers.get(fallback))
            .cloned()
    };
    if let Some(v) = pick("X-Apple-I-MD", "X-Apple-MD") {
        tokens.md = v;
    }
    if let Some(v) = pick("X-Apple-I-MD-LU", "X-Apple-MD-LU") {
        tokens.md_lu = v;
    }
    if let Some(v) = pick("X-Apple-I-MD-M", "X-Apple-MD-M") {
        tokens.md_m = v;
    }
    tokens
}

/// Resolve the `(device_id, serial)` pair, using real identifiers on macOS to
/// avoid Apple error 433.
fn machine_identifiers() -> (String, String) {
    #[cfg(target_os = "macos")]
    {
        (
            machine_udid().unwrap_or_else(|| FALLBACK_DEVICE_ID.to_string()),
            machine_serial_number().unwrap_or_else(|| "0".to_string()),
        )
    }
    #[cfg(not(target_os = "macos"))]
    {
        (FALLBACK_DEVICE_ID.to_string(), "0".to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_anisette_has_required_keys() {
        let data = generate_anisette();
        let cpd = data.cpd.as_object().unwrap();

        assert!(cpd.contains_key("ak"));
        assert!(cpd.contains_key("bootstrap"));
        assert!(cpd.contains_key("cl"));
        assert!(cpd.contains_key("dt"));
        assert!(cpd.contains_key("icscrec"));
        assert!(cpd.contains_key("loc"));
        assert!(cpd.contains_key("os"));
        assert!(cpd.contains_key("p"));
        assert!(cpd.contains_key("pbe"));
        assert!(cpd.contains_key("prkgen"));
        assert!(cpd.contains_key("sv"));
        assert!(cpd.contains_key("svct"));
        assert!(cpd.contains_key("v"));
        assert!(cpd.contains_key("X-Apple-I-Client-Time"));
        assert!(cpd.contains_key("X-Apple-I-TimeZone"));
        assert!(cpd.contains_key("X-Apple-I-Locale"));
        assert!(cpd.contains_key("X-Apple-I-MD"));
        assert!(cpd.contains_key("X-Apple-I-MD-LU"));
        assert!(cpd.contains_key("X-Apple-I-MD-M"));
        assert!(cpd.contains_key("X-Apple-I-MD-RINFO"));
        assert!(cpd.contains_key("X-Mme-Device-Id"));
        assert!(cpd.contains_key("X-Apple-I-SRL-NO"));
        assert!(cpd.contains_key("X-MMe-Client-Info"));
    }

    #[test]
    fn generate_anisette_headers_match_cpd() {
        let data = generate_anisette();
        let cpd = data.cpd.as_object().unwrap();

        for (key, value) in [
            ("X-Apple-I-Client-Time", "X-Apple-I-Client-Time"),
            ("X-Apple-I-TimeZone", "X-Apple-I-TimeZone"),
            ("X-Apple-I-Locale", "X-Apple-I-Locale"),
            ("X-Apple-I-MD", "X-Apple-I-MD"),
            ("X-Apple-I-MD-LU", "X-Apple-I-MD-LU"),
            ("X-Apple-I-MD-M", "X-Apple-I-MD-M"),
            ("X-Apple-I-MD-RINFO", "X-Apple-I-MD-RINFO"),
            ("X-Mme-Device-Id", "X-Mme-Device-Id"),
            ("X-Apple-I-SRL-NO", "X-Apple-I-SRL-NO"),
            ("X-MMe-Client-Info", "X-MMe-Client-Info"),
        ] {
            let header_val = data.headers.get(key).unwrap();
            let cpd_val = cpd.get(value).unwrap().as_str().unwrap();
            assert_eq!(header_val, cpd_val);
        }
    }
}
