//! Anisette / Client Provisioning Data (CPD) for Apple `GrandSlam`.
//!
//! Apple's `GrandSlam` authentication requires device metadata (CPD) embedded
//! in the SRP request plist. This module generates realistic simulated
//! device data.

use base64::Engine;
use serde_json::Value as JsonValue;
use std::collections::HashMap;
use std::time::SystemTime;

#[cfg(target_os = "macos")]
use super::aoskit::{machine_serial_number, machine_udid, retrieve_otp_headers};
#[cfg(not(target_os = "macos"))]
use super::aoskit_fallback::retrieve_otp_headers;

/// Device provisioning data bundled with HTTP headers.
#[derive(Debug, Clone)]
pub struct AnisetteData {
    /// Extra HTTP headers to attach to `GrandSlam` requests.
    pub headers: HashMap<String, String>,
    /// The `cpd` plist dictionary to embed in SRP request bodies.
    pub cpd: JsonValue,
}

/// Returns the local user's `GeneratedUID` on macOS, if available.
#[cfg(target_os = "macos")]
fn get_local_user_uuid() -> Option<String> {
    let username = std::env::var("USER").ok()?;
    let output = std::process::Command::new("dscl")
        .args([
            "/Search",
            "-read",
            &format!("/Users/{username}"),
            "GeneratedUID",
        ])
        .output()
        .ok()?;
    let stdout = String::from_utf8(output.stdout).ok()?;
    // Parse "GeneratedUID: AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA"
    stdout
        .split_whitespace()
        .nth(1)
        .map(|s| s.trim().to_string())
}

#[cfg(not(target_os = "macos"))]
fn get_local_user_uuid() -> Option<String> {
    None
}

/// Generate Anisette / CPD data.
pub fn generate_anisette() -> AnisetteData {
    let time = iso8601_now();
    let timezone = "UTC".to_string();
    let locale = std::env::var("LANG")
        .unwrap_or_else(|_| "en_US".into())
        .split('.')
        .next()
        .unwrap_or("en_US")
        .to_string();

    // X-Apple-I-MD and X-Apple-I-MD-M are cryptographic OTP tokens generated by
    // Apple's proprietary CoreADI/AOSKit libraries. On macOS we try to load the
    // real values via AOSKit.framework; on other platforms we use placeholders.
    let mut md =
        base64::engine::general_purpose::STANDARD.encode(md5::compute("ipakeep-mac").as_slice());
    let mut md_lu = "A1B2C3D4-E5F6-7890-1234-567890ABCDEF".to_string();
    let mut md_m =
        base64::engine::general_purpose::STANDARD.encode(md5::compute("MacBookPro18,3").as_slice());

    if let Some(headers) = retrieve_otp_headers("-2") {
        // AOSUtilities may return keys with or without the `-I-` segment;
        // try both variants.
        if let Some(v) = headers
            .get("X-Apple-I-MD")
            .or_else(|| headers.get("X-Apple-MD"))
        {
            md.clone_from(v);
        }
        if let Some(v) = headers
            .get("X-Apple-I-MD-LU")
            .or_else(|| headers.get("X-Apple-MD-LU"))
        {
            md_lu.clone_from(v);
        }
        if let Some(v) = headers
            .get("X-Apple-I-MD-M")
            .or_else(|| headers.get("X-Apple-MD-M"))
        {
            md_m.clone_from(v);
        }
    }

    // Use real machine identifiers on macOS to avoid Apple error 433.
    #[cfg(target_os = "macos")]
    let device_id =
        machine_udid().unwrap_or_else(|| "FEDCBA09-8765-4321-0FED-CBA987654321".to_string());
    #[cfg(not(target_os = "macos"))]
    let device_id = "FEDCBA09-8765-4321-0FED-CBA987654321".to_string();

    #[cfg(target_os = "macos")]
    let serial = machine_serial_number().unwrap_or_else(|| "0".to_string());
    #[cfg(not(target_os = "macos"))]
    let serial = "0".to_string();

    #[cfg(target_os = "macos")]
    if let Some(user_uuid) = get_local_user_uuid() {
        md_lu = user_uuid;
    }

    let rinfo = "17106176";

    let client_info = "<MacBookPro18,3> <Mac OS X;15.2;24C5089c> <com.apple.AOSKit/282 (com.apple.dt.Xcode/3594.4.19)>".to_string();

    let mut headers = HashMap::new();
    headers.insert("X-Apple-I-Client-Time".into(), time.clone());
    headers.insert("X-Apple-I-TimeZone".into(), timezone.clone());
    headers.insert("X-Apple-I-Locale".into(), locale.clone());
    headers.insert("X-Apple-I-MD".into(), md.clone());
    headers.insert("X-Apple-I-MD-LU".into(), md_lu.clone());
    headers.insert("X-Apple-I-MD-M".into(), md_m.clone());
    headers.insert("X-Apple-I-MD-RINFO".into(), rinfo.into());
    headers.insert("X-Mme-Device-Id".into(), device_id.clone());
    headers.insert("X-Apple-I-SRL-NO".into(), serial.clone());
    headers.insert("X-MMe-Client-Info".into(), client_info.clone());

    let cpd = serde_json::json!({
        "ak": "anisette-v3",
        "bootstrap": "true",
        "cl": locale,
        "dt": "MacBookPro18,3",
        "icscrec": "true",
        "loc": timezone,
        "os": "macOS 15.2",
        "p": "api",
        "pbe": "false",
        "prkgen": "true",
        "sv": "24C5089c",
        "svct": "iCloud",
        "tk": "01",
        "v": "2",
        "X-Apple-I-Client-Time": time,
        "X-Apple-I-TimeZone": timezone,
        "X-Apple-I-Locale": locale,
        "X-Apple-I-MD": md,
        "X-Apple-I-MD-LU": md_lu,
        "X-Apple-I-MD-M": md_m,
        "X-Apple-I-MD-RINFO": rinfo,
        "X-Mme-Device-Id": device_id,
        "X-Apple-I-SRL-NO": serial,
        "X-MMe-Client-Info": client_info,
    });

    AnisetteData { headers, cpd }
}

/// Format the current system time as ISO 8601 (RFC 3339).
fn iso8601_now() -> String {
    let now = SystemTime::now();
    let dur = now
        .duration_since(SystemTime::UNIX_EPOCH)
        .expect("system time before 1970");
    let secs = dur.as_secs();
    let nanos = dur.subsec_nanos();

    let (year, month, day, hour, min, sec) = unix_to_utc(secs);
    format!(
        "{:04}-{:02}-{:02}T{:02}:{:02}:{:02}.{:03}Z",
        year,
        month,
        day,
        hour,
        min,
        sec,
        nanos / 1_000_000
    )
}

/// Convert Unix seconds to UTC date/time components.
fn unix_to_utc(seconds: u64) -> (u32, u32, u32, u32, u32, u32) {
    let days = seconds / 86400;
    let rem = seconds % 86400;
    let hour = (rem / 3600) as u32;
    let min = ((rem % 3600) / 60) as u32;
    let sec = (rem % 60) as u32;

    let mut year = 1970u32;
    let mut days_left = i64::try_from(days).expect("days since 1970 fits in i64");

    loop {
        let year_days = if is_leap_year(year) { 366 } else { 365 };
        if days_left < year_days {
            break;
        }
        days_left -= year_days;
        year += 1;
    }

    let month_days = [
        31,
        if is_leap_year(year) { 29 } else { 28 },
        31,
        30,
        31,
        30,
        31,
        31,
        30,
        31,
        30,
        31,
    ];

    let mut month = 1u32;
    for &md in &month_days {
        if days_left < md {
            break;
        }
        days_left -= md;
        month += 1;
    }

    let day = u32::try_from(days_left + 1).expect("day of year fits in u32");
    (year, month, day, hour, min, sec)
}

fn is_leap_year(year: u32) -> bool {
    (year.is_multiple_of(4) && !year.is_multiple_of(100)) || year.is_multiple_of(400)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_anisette_has_required_keys() {
        let data = generate_anisette();
        let cpd = data.cpd.as_object().unwrap();

        assert!(cpd.contains_key("ak"));
        assert!(cpd.contains_key("bootstrap"));
        assert!(cpd.contains_key("cl"));
        assert!(cpd.contains_key("dt"));
        assert!(cpd.contains_key("icscrec"));
        assert!(cpd.contains_key("loc"));
        assert!(cpd.contains_key("os"));
        assert!(cpd.contains_key("p"));
        assert!(cpd.contains_key("pbe"));
        assert!(cpd.contains_key("prkgen"));
        assert!(cpd.contains_key("sv"));
        assert!(cpd.contains_key("svct"));
        assert!(cpd.contains_key("v"));
        assert!(cpd.contains_key("X-Apple-I-Client-Time"));
        assert!(cpd.contains_key("X-Apple-I-TimeZone"));
        assert!(cpd.contains_key("X-Apple-I-Locale"));
        assert!(cpd.contains_key("X-Apple-I-MD"));
        assert!(cpd.contains_key("X-Apple-I-MD-LU"));
        assert!(cpd.contains_key("X-Apple-I-MD-M"));
        assert!(cpd.contains_key("X-Apple-I-MD-RINFO"));
        assert!(cpd.contains_key("X-Mme-Device-Id"));
        assert!(cpd.contains_key("X-Apple-I-SRL-NO"));
        assert!(cpd.contains_key("X-MMe-Client-Info"));
    }

    #[test]
    fn generate_anisette_headers_match_cpd() {
        let data = generate_anisette();
        let cpd = data.cpd.as_object().unwrap();

        for (key, value) in [
            ("X-Apple-I-Client-Time", "X-Apple-I-Client-Time"),
            ("X-Apple-I-TimeZone", "X-Apple-I-TimeZone"),
            ("X-Apple-I-Locale", "X-Apple-I-Locale"),
            ("X-Apple-I-MD", "X-Apple-I-MD"),
            ("X-Apple-I-MD-LU", "X-Apple-I-MD-LU"),
            ("X-Apple-I-MD-M", "X-Apple-I-MD-M"),
            ("X-Apple-I-MD-RINFO", "X-Apple-I-MD-RINFO"),
            ("X-Mme-Device-Id", "X-Mme-Device-Id"),
            ("X-Apple-I-SRL-NO", "X-Apple-I-SRL-NO"),
            ("X-MMe-Client-Info", "X-MMe-Client-Info"),
        ] {
            let header_val = data.headers.get(key).unwrap();
            let cpd_val = cpd.get(value).unwrap().as_str().unwrap();
            assert_eq!(header_val, cpd_val);
        }
    }
}
